# Generated by Django 5.1.4 on 2025-04-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_emp_hiredate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='hiredate',
            field=models.DateField(default='2000-09-20'),
        ),
    ]
